### ISSUE TITLE
panic safety: double drop may happen in two functions

### ISSUE THREAD

**Issue by JOE1994** [okready/scratchpad#1]
Hello,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

Two functions allow double-drop of an object upon panic: `<T as traits::SliceMoveSource<[<T as traits::Array>::Item]>>::move_elements()`, `<std::boxed::Box<T> as traits::SliceMoveSource<T>>::move_elements()`. Both functions take user-provided closure as parameter, and a double drop of an object happens upon panic inside the user-provided closure.

## Reproduction

Below is an example program that exhibits undefined behavior using safe APIs of `scratchpad`.

<details><summary>Show Detail</summary>
<p>

struct `Foo` is dropped twice upon panic in user-provided closure.

```rust
#![forbid(unsafe_code)]
use scratchpad::SliceLike;
use scratchpad::SliceMoveSource;

#[derive(Clone, Debug)]
struct Foo(i32);

impl Drop for Foo {
    fn drop(&mut self) {
        // This message is printed twice, indicating double-free.
        println!("I'm dropping {}", self.0);
    }
}

fn main() {
    let mut mybox = [Foo(1234); 1];

    mybox.move_elements(|s| {
        panic!("Unexpected panic");
        dbg!(s);
    });
}
```

Output:
```
thread 'main' panicked at 'Unexpected panic', src/main.rs:33:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
I'm dropping 1234
I'm dropping 1234

Return code 101
```

### Tested Environment

* Crate: scratchpad
* Version: 1.3.0
* OS: Ubuntu 18.04.5 LTS
* Rustc version: rustc 1.50.0 (cb75ad5db 2021-02-10)

</p>
</details>

**Comment by okready** [comment]
Thanks, @JOE1994. I believe should be able to look into this later on this evening.

**Comment by okready** [comment]
I put in a fix that should address the issue, along with what was effectively the same issue in the `SliceMoveSourceCollection` trait. With your repro example, I only get one "I'm dropping 1234" message as expected.

I'll cut a 1.3.1 release with the fix. Thanks again for the heads-up!

**Comment by okready** [comment]
I've gone ahead and yanked all previous 1.x releases as well. 0.x releases are likely unaffected since they didn't have the same functionality provided by these traits.
